name: Build Unsigned
on:
  workflow_dispatch:

jobs:
  BuildUnsigned:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon app:assembleMeta-AlphaRelease
